import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import { IReviewProvider } from "./providers/IReviewProvider";

/**
 * Agent handles the processing of changed files and generation of review files.
 *
 * Current implementation: Local stub that writes a review markdown file with
 * timestamp, commit range, and file list.
 *
 * Future: Will integrate with Copilot Agent endpoint to generate AI-powered reviews.
 */
export class Agent {
  private outputChannel: vscode.OutputChannel;
  private workspaceRoot: string;
  private provider?: IReviewProvider;

  constructor(
    workspaceRoot: string,
    outputChannel: vscode.OutputChannel,
    provider?: IReviewProvider
  ) {
    this.workspaceRoot = workspaceRoot;
    this.outputChannel = outputChannel;
    this.provider = provider;
  }

  /**
   * Process changed files and generate a review.
   *
   * @param files List of changed file paths
   * @param oldHash Previous commit hash
   * @param newHash New commit hash
   */
  async processChanges(
    files: string[],
    oldHash: string,
    newHash: string
  ): Promise<void> {
    try {
      this.outputChannel.appendLine(
        "[Agent] Processing changes for commit range: " +
          oldHash +
          ".." +
          newHash
      );

      // Generate review content — prefer pluggable provider if available
      let reviewContent: string;
      if (this.provider) {
        try {
          reviewContent = await this.provider.generateReview(
            files,
            oldHash,
            newHash
          );
        } catch (err) {
          this.outputChannel.appendLine(
            "[Agent] Provider failed, falling back to local generator: " +
              (err instanceof Error ? err.message : String(err))
          );
          reviewContent = this.generateReviewContent(files, oldHash, newHash);
        }
      } else {
        reviewContent = this.generateReviewContent(files, oldHash, newHash);
      }

      // Write review file
      await this.writeReviewFile(reviewContent);

      this.outputChannel.appendLine(
        "[Agent] Review file generated successfully"
      );
    } catch (error) {
      if (error instanceof Error) {
        this.outputChannel.appendLine(
          "[Agent] Error processing changes: " + error.message
        );
      }
    }
  }

  /**
   * Generate review content (stub implementation).
   *
   * This is a placeholder that creates a basic markdown structure.
   * Future: Replace with actual AI review generation.
   */
  private generateReviewContent(
    files: string[],
    oldHash: string,
    newHash: string
  ): string {
    const timestamp = new Date().toISOString();
    const fileList = files.map((f) => `- ${f}`).join("\n");

    return `# Code Review

**Generated**: ${timestamp}

**Commit Range**: \`${oldHash}\` → \`${newHash}\`

## Changed Files (${files.length})

${fileList}

## Review

This is an automated review stub. Future versions will include AI-generated analysis via Copilot Agent integration.

---
*Generated by Continuous AI Reviewer*
`;
  }

  /**
   * Write the review content to review/review.md
   */
  private async writeReviewFile(content: string): Promise<void> {
    const reviewDir = path.join(this.workspaceRoot, "review");
    const reviewFile = path.join(reviewDir, "review.md");

    // Create review directory if it doesn't exist
    if (!fs.existsSync(reviewDir)) {
      fs.mkdirSync(reviewDir, { recursive: true });
      this.outputChannel.appendLine("[Agent] Created review directory");
    }

    // Write review file
    fs.writeFileSync(reviewFile, content, "utf-8");
    this.outputChannel.appendLine("[Agent] Review written to: " + reviewFile);
  }
}
